apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: memory-autoscale 
  namespace: bullseye
spec:
  scaleTargetRef:
    apiVersion: apps/v1 
    name: bookmystuff-service-app 
    kind: DeploymentConfig 
  minReplicas: 3 
  maxReplicas: 6 
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        name: memory-percent
        type: Utilization
        averageUtilization: 40 